name: Feature Request
description: Propose a new capability or improvement to an existing system.
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template to propose a new feature or a meaningful improvement to an existing system.
        Before submitting, search existing issues to avoid duplicates.

  - type: input
    id: service
    attributes:
      label: Target Service
      description: Which service or repository would this feature affect? (e.g., OpsLedger, Arthemiz, Vendas3D, Sentinel, SystemHealth)
      placeholder: "e.g., Vendas3D"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem or gap this feature addresses. Focus on the problem, not the solution.
      placeholder: "As a tenant administrator, I cannot currently..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the desired behavior or capability. Be specific about the expected interface, API contract, or UX change.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative approaches have been evaluated? Why were they rejected?
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Business Priority
      description: What is the estimated business impact of this feature?
      options:
        - "Critical — blocking a production use case"
        - "High — significant user or operator impact"
        - "Medium — meaningful improvement"
        - "Low — nice to have"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Mockups, related issues, external references, or any other information relevant to this request.
    validations:
      required: false
