name: auto-assign

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  auto_assign:
    uses: ArthemizLabs/.github/.github/workflows/auto-assign.yml@<SHA>
    with:
      assignees: A4thu4
      max_assignees: 1
    secrets: inherit
