name: Auto Assign

on:
  workflow_call:
    inputs:
      assignees:
        description: "Lista de usuários separados por vírgula a serem atribuídos."
        required: true
        type: string
      max_assignees:
        description: "Quantidade máxima de pessoas a atribuir automaticamente."
        required: false
        default: 1
        type: number
    secrets:
      github_token:
        description: "Token com permissão para escrever em issues e pull requests. Usa GITHUB_TOKEN por padrão."
        required: false

jobs:
  auto_assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Definir responsáveis automaticamente
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ inputs.assignees }}
          numOfAssignee: ${{ inputs.max_assignees }}
